name: Release express-app

on:
  push:
    branches:
      - main
    paths:
      - 'express-app/**'
      - '.github/workflows/express-app.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    # We need to login so we can later push the image without issues. 
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push express app
    - name: Build and push express app
      uses: docker/build-push-action@v5
      with:
        context: express-app
        push: true
        tags: thannin/express-app:latest

